FROM ubuntu:latest

# Set environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_VERSION=3.4.0
ENV SPARK_VERSION=3.4.3
ENV HADOOP_HOME=/opt/hadoop
ENV SPARK_HOME=/opt/spark

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk wget tar curl && \
    apt-get clean

RUN wget -qO- https://downloads.apache.org/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz | tar xvz -C /opt/ && \
    mv /opt/hadoop-$HADOOP_VERSION $HADOOP_HOME && \
    rm -rf $HADOOP_HOME/share/doc

RUN wget -qO- https://downloads.apache.org/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop3.tgz | tar xvz -C /opt/ && \
    mv /opt/spark-$SPARK_VERSION-bin-hadoop3 $SPARK_HOME && \
    rm -rf $SPARK_HOME/examples $SPARK_HOME/data

ENV PATH=$PATH:$HADOOP_HOME/bin:$SPARK_HOME/bin
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV SPARK_CONF_DIR=$SPARK_HOME/conf

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install pyspark==3.4.3

WORKDIR /app

COPY . /app

CMD ["python3", "/app/tests/pyspark_data_processor.py"]

